"""update

Revision ID: 9add7a854fb7
Revises: 6873f791bcd0
Create Date: 2024-08-21 14:43:33.808526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9add7a854fb7"
down_revision: Union[str, None] = "6873f791bcd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees") as batch_op:

        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_employees_team_id", "teams", ["team_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees") as batch_op:
        batch_op.drop_constraint("fk_employees_team_id", type_="foreignkey")
        batch_op.drop_column("team_id")
    # ### end Alembic commands ###
